package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.InvokeBy;
import com.kwad.components.core.innerEc.InnerEcUserLoginBindInfo;
import com.kwad.components.core.innerEc.live.a.a;
import com.kwad.components.core.innerEc.live.a.d;
import com.kwad.components.core.innerEc.live.a.m;
import com.kwad.components.core.innerEc.live.a.o;
import com.kwad.components.core.innerEc.logger.BaseInnerEcMsg;
import com.kwad.components.core.innerEc.logger.InnerEcError;
import com.kwad.components.core.innerEc.logger.InnerEcEvent;
import com.kwad.components.core.innerEc.qcpx.ReceiveQcpxBody;
import com.kwad.components.core.pfmonitor.model.DiskReportInfo;
import com.kwad.components.core.video.a.d;
import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.jsPublicBridge.a.a;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.a.a;
import com.kwad.components.core.webview.jshandler.a.e;
import com.kwad.components.core.webview.jshandler.a.f;
import com.kwad.components.core.webview.jshandler.ag;
import com.kwad.components.core.webview.jshandler.ah;
import com.kwad.components.core.webview.jshandler.aj;
import com.kwad.components.core.webview.jshandler.ak;
import com.kwad.components.core.webview.jshandler.an;
import com.kwad.components.core.webview.jshandler.ao;
import com.kwad.components.core.webview.jshandler.ap;
import com.kwad.components.core.webview.jshandler.as;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.au;
import com.kwad.components.core.webview.jshandler.av;
import com.kwad.components.core.webview.jshandler.ay;
import com.kwad.components.core.webview.jshandler.ba;
import com.kwad.components.core.webview.jshandler.be;
import com.kwad.components.core.webview.jshandler.bf;
import com.kwad.components.core.webview.jshandler.bg;
import com.kwad.components.core.webview.jshandler.bj;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.i;
import com.kwad.components.core.webview.jshandler.j;
import com.kwad.components.core.webview.jshandler.l;
import com.kwad.components.core.webview.jshandler.m;
import com.kwad.components.core.webview.jshandler.q;
import com.kwad.components.core.webview.jshandler.u;
import com.kwad.components.core.webview.jshandler.v;
import com.kwad.components.core.webview.jshandler.y;
import com.kwad.components.core.webview.tachikoma.b.h;
import com.kwad.components.core.webview.tachikoma.b.u;
import com.kwad.components.core.webview.tachikoma.b.x;
import com.kwad.sdk.kgeo.KGeoInfo;
import com.kwad.sdk.mobileid.UaidInfo;
import com.kwad.sdk.monitor.MediaMessageInfo;
import com.kwad.sdk.monitor.b;
import com.kwad.sdk.resourceCache.model.WarmUpReportMessage;

/* loaded from: classes4.dex */
public final class di {
    @InvokeBy(invokerClass = hl.class, methodId = "registerHolder")
    public static void LS() {
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.d.class, new bt());
        hl.LT().put(com.kwad.components.core.innerEc.followuser.a.class, new fe());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.w.class, new nr());
        hl.LT().put(d.a.class, new nx());
        hl.LT().put(m.a.class, new ec());
        hl.LT().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new ad());
        hl.LT().put(InnerEcEvent.class, new gp());
        hl.LT().put(com.kwad.components.core.innerEc.followuser.b.class, new ff());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.e.class, new ic());
        hl.LT().put(com.kwad.components.core.offline.moitor.b.class, new jo());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.q.class, new kd());
        hl.LT().put(ao.b.class, new fz());
        hl.LT().put(com.kwad.components.core.webview.a.c.class, new jr());
        hl.LT().put(l.a.class, new fw());
        hl.LT().put(ba.a.class, new ih());
        hl.LT().put(com.kwad.components.core.innerEc.live.f.b.class, new lu());
        hl.LT().put(y.a.class, new x());
        hl.LT().put(a.C0534a.class, new iu());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.o.class, new jq());
        hl.LT().put(bg.a.class, new ge());
        hl.LT().put(as.a.class, new jx());
        hl.LT().put(j.a.class, new fu());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.s.class, new lr());
        hl.LT().put(com.kwad.components.core.innerEc.live.base.c.class, new lg());
        hl.LT().put(ak.a.class, new gg());
        hl.LT().put(com.kwad.components.core.offline.moitor.d.class, new nq());
        hl.LT().put(bj.a.class, new hk());
        hl.LT().put(au.a.class, new bl());
        hl.LT().put(av.a.class, new bu());
        hl.LT().put(ReceiveQcpxBody.class, new ko());
        hl.LT().put(b.a.class, new lk());
        hl.LT().put(DiskReportInfo.class, new ea());
        hl.LT().put(com.kwad.components.core.webview.a.b.class, new jp());
        hl.LT().put(u.a.class, new mu());
        hl.LT().put(com.kwad.components.core.m.a.class, new v());
        hl.LT().put(com.kwad.components.core.page.c.a.class, new hu());
        hl.LT().put(j.b.class, new fv());
        hl.LT().put(com.kwad.components.core.innerEc.live.base.b.class, new ib());
        hl.LT().put(com.kwad.components.core.pfmonitor.model.b.class, new eb());
        hl.LT().put(com.kwad.components.core.pfmonitor.model.a.class, new dz());
        hl.LT().put(q.a.class, new iw());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.h.class, new ds());
        hl.LT().put(com.kwad.components.core.pfmonitor.model.f.class, new kr());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.k.class, new hi());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.a.class, new o());
        hl.LT().put(a.C0564a.class, new cl());
        hl.LT().put(u.b.class, new mk());
        hl.LT().put(d.a.class, new hz());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.f.class, new cr());
        hl.LT().put(a.C0560a.class, new ed());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.p.class, new jv());
        hl.LT().put(bf.a.class, new nd());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.z.class, new od());
        hl.LT().put(aj.a.class, new ns());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.g.class, new cu());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.y.class, new nz());
        hl.LT().put(com.kwad.components.core.video.a.e.class, new og());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.c.class, new hw());
        hl.LT().put(com.kwad.sdk.a.a.a.a.class, new gw());
        hl.LT().put(i.a.class, new ft());
        hl.LT().put(f.a.class, new fq());
        hl.LT().put(e.a.class, new lm());
        hl.LT().put(a.C0563a.class, new an());
        hl.LT().put(g.a.class, new fr());
        hl.LT().put(v.b.class, new mq());
        hl.LT().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new af());
        hl.LT().put(an.a.class, new dl());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.b.class, new hp());
        hl.LT().put(InnerEcError.class, new go());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.u.class, new lv());
        hl.LT().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new ae());
        hl.LT().put(a.c.class, new jh());
        hl.LT().put(ap.b.class, new hh());
        hl.LT().put(x.a.class, new bp());
        hl.LT().put(ah.a.class, new kh());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.m.class, new hv());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.r.class, new lp());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.f.class, new id());
        hl.LT().put(ay.a.class, new oh());
        hl.LT().put(ag.a.class, new kg());
        hl.LT().put(h.a.class, new fs());
        hl.LT().put(e.b.class, new gj());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.t.class, new ls());
        hl.LT().put(f.a.class, new cq());
        hl.LT().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new ho());
        hl.LT().put(a.C0562a.class, new hn());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.a.class, new et());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.i.class, new fa());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.d.class, new hx());
        hl.LT().put(BaseInnerEcMsg.class, new cb());
        hl.LT().put(com.kwad.components.core.b.b.class, new hr());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.i.class, new oj());
        hl.LT().put(d.b.class, new ny());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.x.class, new nv());
        hl.LT().put(m.a.class, new gu());
        hl.LT().put(com.kwad.components.core.innerEc.live.config.net.g.class, new ig());
        hl.LT().put(o.a.class, new ht());
        hl.LT().put(at.a.class, new bi());
        hl.LT().put(UaidInfo.class, new nn());
        hl.LT().put(m.b.class, new gv());
        hl.LT().put(h.b.class, new kf());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.j.class, new fx());
        hl.LT().put(KGeoInfo.class, new hm());
        hl.LT().put(com.kwad.components.core.innerEc.live.base.e.class, new li());
        hl.LT().put(a.b.class, new eg());
        hl.LT().put(au.b.class, new bm());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.n.class, new iy());
        hl.LT().put(com.kwad.components.core.innerEc.live.f.a.class, new lt());
        hl.LT().put(MediaMessageInfo.class, new is());
        hl.LT().put(b.C0633b.class, new ll());
        hl.LT().put(MediaMessageInfo.MediaPermissionInfo.class, new it());
        hl.LT().put(InnerEcUserLoginBindInfo.class, new gr());
        hl.LT().put(com.kwad.components.core.innerEc.live.base.d.class, new lh());
        hl.LT().put(ap.a.class, new hg());
        hl.LT().put(be.a.class, new oe());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.e.class, new cj());
        hl.LT().put(WebCardVideoPositionHandler.VideoPosition.class, new oc());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.c.class, new br());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.b.class, new bn());
        hl.LT().put(com.kwad.components.core.webview.tachikoma.c.v.class, new mj());
        hl.LT().put(WarmUpReportMessage.class, new of());
    }
}
